name: C++ CI with Bazel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v3

      - name: Build and test with Bazel and GoogleTest
        run: bazelisk test //...
